# Overwrite the theme
defaults:
    -
      scope:
        path: ""
      values:
        layout: "main"
        
title: ORMAP Tools
email: bwilson@co.clatsop.or.us
description: >- # this means to ignore newlines until "baseurl:"
  Tools for developing an Oregon statewide cadastral base map
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
#plugins:
#  - jekyll-feed

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

